//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::book_managers::Entity as BookManagers;
pub use super::books::Entity as Books;
pub use super::borrow_records::Entity as BorrowRecords;
pub use super::users::Entity as Users;
