//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "book_status")]
pub enum BookStatus {
    #[sea_orm(string_value = "AVAILABLE")]
    Available,
    #[sea_orm(string_value = "BORROWED")]
    Borrowed,
    #[sea_orm(string_value = "ON_HOLD")]
    OnHold,
    #[sea_orm(string_value = "MAINTENANCE")]
    Maintenance,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "borrow_status")]
pub enum BorrowStatus {
    #[sea_orm(string_value = "BORROWED")]
    Borrowed,
    #[sea_orm(string_value = "RETURNED")]
    Returned,
    #[sea_orm(string_value = "OVERDUE")]
    Overdue,
}
