[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sea-orm = { workspace = true }
